### ISSUE TITLE
Release to OSSRH staging repository

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/interceptor-api#13]
- [ ] Uptake new Eclipse versions of dependencies (if any). Use [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) wiki to find components versions to use.

- [ ] Release to OSSRH staging repository

- [ ] Update [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) with released version number.

**Comment by m0mus** [comment]
Roman is working on it.

**Comment by bravehorsie** [comment]
https://oss.sonatype.org/content/repositories/staging/jakarta/interceptor/jakarta.interceptor-api/1.2.3/
GF tracker page updated

**Comment by vinayvishal** [comment]
@bravehorsie This needs to be re-staged as artefacts are not available at the specified location.
