### ISSUE TITLE
Jakarta release has wrong OSGi Bundle-SymbolicName

### ISSUE THREAD

**Issue by rfelcman** [eclipse-ee4j/interceptor-api#22]
Jakarta release of this API has wrong value of OSGi Bundle-SymbolicName in MANIFEST.MF.
Current value is _javax.interceptor-api_ but expected value could be _jakarta.interceptor-api_ .

**Comment by Tomas-Kraus** [comment]
Fixed in https://github.com/eclipse-ee4j/interceptor-api/pull/24 and https://github.com/eclipse-ee4j/interceptor-api/pull/23
