### ISSUE TITLE
Public Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/interceptor-api#25]
Last CTS runs indicate no failures in this component. It's time to make a public release. Before the release make sure that Eclipse Release Review is passed and all dependencies have been released.

**Comment by arjantijms** [comment]
Depends on jakarta.annotation-api and jakarta.ejb-api.

Annotations has been released:

* https://mvnrepository.com/artifact/jakarta.annotation/jakarta.annotation-api

As has EJB:

* https://mvnrepository.com/artifact/jakarta.ejb/jakarta.ejb-api

**Comment by arjantijms** [comment]
1.2.3 release review was successful: 

* https://projects.eclipse.org/projects/ee4j.interceptors/reviews/1.2.3-release-review

**Comment by arjantijms** [comment]
Release done:

* https://repo1.maven.org/maven2/jakarta/interceptor/jakarta.interceptor-api/1.2.3/
