### ISSUE TITLE
Artifacts are missing legal files

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/interceptor-api#28]
as is required and documented in https://www.eclipse.org/projects/handbook/#legaldoc

**Comment by starksm64** [comment]
This has been resolved for a while.

└> jar -tf target/jakarta.interceptor-api-2.1.0-SNAPSHOT.jar 
META-INF/MANIFEST.MF
META-INF/
jakarta/
jakarta/interceptor/
META-INF/maven/
META-INF/maven/jakarta.interceptor/
META-INF/maven/jakarta.interceptor/jakarta.interceptor-api/
META-INF/LICENSE.md
META-INF/NOTICE.md
