### ISSUE TITLE
Update Scope Statement for Jakarta Interceptors Project

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/interceptor-api#29]
Update the scope statement for the project: https://projects.eclipse.org/projects/ee4j.jakartaee-platform/governance

See https://docs.google.com/spreadsheets/d/1FPLjo_DJDOQngVtdrYgaDk98d9NBG-0ODgdmOG3LOsI/edit?usp=sharing for examples.

**Comment by smillidge** [comment]
@arjantijms @dblevins can you progress the scope statement?

**Comment by waynebeaton** [comment]
How about this?

> Jakarta Interceptors defines a means of interposing on business method invocations and specific events—such as lifecycle events and timeout events—that occur on instances of Jakarta EE components and other managed classes.

**Comment by ivargrimstad** [comment]
> How about this?
> 
> > Jakarta Interceptors defines a means of interposing on business method invocations and specific events—such as lifecycle events and timeout events—that occur on instances of Jakarta EE components and other managed classes.

Yes, go with it!
