### ISSUE TITLE
Dependencies never be used

### ISSUE THREAD

**Issue by rieonke** [eclipse-ee4j/interceptor-api#31]
The interceptor api declared 2 deps `common-annotations` and `ejb` in the pom.xml,
but none of them has been imported,  so can we remove it?
https://github.com/eclipse-ee4j/interceptor-api/blob/8eb1e608ad81c06ddfd147a077c06cad2b46f9a2/pom.xml#L322-L334
```
➜  interceptor-api git:(EE4J_8) find . -name \*.java -exec grep "import javax" {} \;
➜  interceptor-api git:(EE4J_8) 
```

**Comment by romain-grecourt** [comment]
These 2 dependencies were not present in `javax.interceptor:javax.interceptor-api`.
They were added by this commit: https://github.com/eclipse-ee4j/interceptor-api/commit/ae60a7951175f9c55b540f799d4e5f8ec720e2d0

These new dependencies are actually exposed transitively, so basically cdi-api now depends on ejb-api:
```
+- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:2.0.2:provided
[INFO] |  +- jakarta.el:jakarta.el-api:jar:3.0.3:provided
[INFO] |  +- jakarta.interceptor:jakarta.interceptor-api:jar:1.2.5:provided
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:provided
[INFO] |  |  \- jakarta.ejb:jakarta.ejb-api:jar:3.2.6:provided
[INFO] |  |     \- jakarta.transaction:jakarta.transaction-api:jar:1.3.2:provided
[INFO] |  \- jakarta.inject:jakarta.inject-api:jar:1.0:provided
```

They are likely used to resolve the javadoc links to both ejb and annotation API.

**Comment by keilw** [comment]
If it's just in the JavaDoc and there is no dependency, not even an optional one, then it could be removed I guess. And the reference ideally should be removed and {@link javax.ejb.Timer} replaced e.g. with {@code javax.ejb.Timer} which has the same formatting effect.

**Comment by arjantijms** [comment]
Fixed by Jonathan @Cousjava 

Thanks to everyone contributing to this. There might be some other specifications that have this same issue, so would be good to look at other specs too for this.

**Comment by jmartisk** [comment]
Hi @arjantijms could we please ask you to get 1.2.6 released soon? MicroProfile is moving to align with  Jakarta EE dependencies and we'd like to avoid having to exclude the EJB dependency on the platform side (EJB clearly doesn't belong into MicroProfile)

**Comment by keilw** [comment]
I guess that's up to a particular feature, there's so much stuff in MicroProfile these days, that even the EJB 3+ that's also used in the Web Profile sounds not unreasonable.
