### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/interceptor-api#5]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by lilian-benoit** [comment]
I can't assign myself this issue

**Comment by m0mus** [comment]
@arjantijms @dblevins do you have any objections?

**Comment by arjantijms** [comment]
Project CI environment has been requested:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=538673

**Comment by arjantijms** [comment]
Interceptors job created, and fully runs. Branch https://github.com/eclipse-ee4j/interceptor-api/tree/1.2.3 created by interceptors bot.
