### ISSUE TITLE
Release CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/interceptor-api#6]
We need to create a release CI/CD pipeline for this project. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)
- [Release job on the new cloud infra](https://wiki.eclipse.org/JakartaEE_New_Infra_Release_Job)

**Comment by lilian-benoit** [comment]
I can't assign myself this issue

**Comment by m0mus** [comment]
@arjantijms @dblevins do you have any objections?

**Comment by m0mus** [comment]
I don't think that #10 fixes this issue. Reopening.

**Comment by arjantijms** [comment]
Interceptors job created, and fully runs. Branch https://github.com/eclipse-ee4j/interceptor-api/tree/1.2.3 created by interceptors bot.
