### ISSUE TITLE
Interceptors specification documentation is malformed

### ISSUE THREAD

**Issue by manovotn** [eclipse-ee4j/interceptor-api#65]
I went looking for the spec doc the other day.
Turns out that the [doc on website](https://jakarta.ee/specifications/interceptors/1.2/interceptors-spec-1.2.pdf) is 5 pages long and contains licences plus first paragraph of chapter one and that's it (for both, 1.2 and 2.x).
Same goes for when you try to build the doc from repo, at least on master branch.

**Comment by arjantijms** [comment]
Thanks for the issue. This will be fixed for the 2.0/Jakarta EE 9 release.
