### ISSUE TITLE
Bug in example in section 2

### ISSUE THREAD

**Issue by ljnelson** [eclipse-ee4j/interceptor-api#72]
Hello; I just noticed this and didn't want it to get lost.

See https://github.com/eclipse-ee4j/interceptor-api/blob/master/spec/src/main/asciidoc/2_interceptor_programming_contract.adoc#timeout-method-interceptor-methods.  The example involves calling `getInfo()` on the timer object returned by [`InvocationContext#getTimer()`](https://jakarta.ee/specifications/interceptors/2.0/apidocs/jakarta/interceptor/InvocationContext.html#getTimer()), which [is of type `Object`](https://jakarta.ee/specifications/interceptors/2.0/apidocs/jakarta/interceptor/InvocationContext.html#getTimer()).  Hence this won't compile.

**Comment by starksm64** [comment]
Included in the #94 PR
