### ISSUE TITLE
Completion steps for Interceptors 2.0

### ISSUE THREAD

**Issue by kazumura** [eclipse-ee4j/interceptor-api#82]
* Specification Committee Member...

- [x]  creates an issue in the specification project that includes the following checklist for the specification project team:

 * Interceptors Specification Project Team...

- [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
- [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
- [x] approve the compatibility request.
- [x] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
- [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by pzygielo** [comment]
Forgive me - as I might be wrong, as I saw it in eclipse-ee4j/jsp-api#195 already. Is that copy&paste template error, or **Concurrency Specification Project Team** is involved in each project indeed?

**Comment by kazumura** [comment]
I'm sorry. This is for Interceptors team.

**Comment by arjantijms** [comment]
spec jars at: https://repo1.maven.org/maven2/jakarta/interceptor/jakarta.interceptor-api/2.0.0/

**Comment by arjantijms** [comment]
Links at https://jakarta.ee/specifications/interceptors/2.0/ look good
