### ISSUE TITLE
The foundational term "business method" is never defined

### ISSUE THREAD

**Issue by ljnelson** [eclipse-ee4j/interceptor-api#87]
Due, probably primarily, to the history of the Interceptors specification, the [specification](https://jakarta.ee/specifications/interceptors/2.0/interceptors-spec-2.0.html) mentions "business method" 16 times but never defines it.

"Business method" [_is_ a well-defined term in the Jakarta EJB specification](https://jakarta.ee/specifications/enterprise-beans/4.0/jakarta-enterprise-beans-spec-core-4.0.html#business-methods), from whose ancestor the original Interceptors specification evolved.  I suspect that the definition found there is the one that should be included here.

**Comment by starksm64** [comment]
I added a definition to the terminology section.
